In [197]:
import pandas as pd
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [198]:
iris_data=pd.read_csv("Iris.csv")

In [199]:
iris_data.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [200]:
le = LabelEncoder()
iris_data["Species"] = le.fit_transform(iris_data["Species"])

In [201]:
iris_data.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        0
1   2            4.9           3.0            1.4           0.2        0
2   3            4.7           3.2            1.3           0.2        0
3   4            4.6           3.1            1.5           0.2        0
4   5            5.0           3.6            1.4           0.2        0

In [202]:
X=iris_data.drop("Species",axis=1)
Y= iris_data["Species"]

In [203]:
X_train,X_test,y_train,y_test=train_test_split( X,Y,test_size=0.2 , random_state=42)

In [204]:
model=LogisticRegression(max_iter=1000)

In [205]:
model.fit(X_train,y_train)
y_pred=model.predict(X_test)
print("predicted y value ", y_pred)
print("Accuracy:", accuracy_score(y_test, y_pred) * 100)
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

predicted y value  [1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
Accuracy: 100.0

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30


Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

In [206]:
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier

In [207]:
iris_data=pd.read_csv("Iris.csv")
iris_data.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [208]:
le=LabelEncoder()
iris_data["Species"]=le.fit_transform(iris_data["Species"])

In [209]:
X=iris_data.drop("Species",axis=1)
Y= iris_data["Species"]    

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [210]:
X_train,X_test,y_train,y_test=train_test_split( X,Y,test_size=0.2 , random_state=42)

In [213]:
model=KNeighborsClassifier()

param_grid={
    "n_neighbors":[1,2,3,4,9],
    "weights":["uniform","distance"],
    "metric":["euclidean","manhattan"]
}

grid= GridSearchCV(model, param_grid, cv=5, scoring="accuracy")

grid.fit(X_train,y_train)
# print("Best Params:", grid.best_params_)
# print("Best Score:", grid.best_score_)
# print("All Results:", grid.cv_results_)
results = pd.DataFrame(grid.cv_results_)
print(results)

    mean_fit_time  std_fit_time  mean_score_time  std_score_time param_metric  \
0        0.004082      0.000430         0.007350        0.000885    euclidean
1        0.002656      0.000864         0.003280        0.001444    euclidean
2        0.003114      0.000793         0.005444        0.001086    euclidean
3        0.002006      0.000279         0.002323        0.000403    euclidean
4        0.002024      0.000420         0.003627        0.000353    euclidean
5        0.002182      0.000044         0.003192        0.000567    euclidean
6        0.002653      0.000410         0.005046        0.000656    euclidean
7        0.003130      0.000568         0.003671        0.001081    euclidean
8        0.002434      0.000180         0.004427        0.000089    euclidean
9        0.002236      0.000099         0.002823        0.000339    euclidean
10       0.002133      0.000080         0.004208        0.000463    manhattan
11       0.002331      0.000251         0.002852        0.000375    manhattan
12       0.002366      0.000100         0.004676        0.000277    manhattan
13       0.002452      0.000096         0.002908        0.000076    manhattan
14       0.003785      0.000507         0.006640        0.001208    manhattan
15       0.003568      0.001146         0.004765        0.000989    manhattan
16       0.003843      0.000790         0.007077        0.000554    manhattan
17       0.003186      0.000776         0.003555        0.000217    manhattan
18       0.002383      0.000284         0.004305        0.000173    manhattan
19       0.002622      0.000535         0.003344        0.000333    manhattan

    param_n_neighbors param_weights  \
0                   1       uniform
1                   1      distance
2                   2       uniform
3                   2      distance
4                   3       uniform
5                   3      distance
6                   4       uniform
7                   4      distance
8                   9       uniform
9                   9      distance
10                  1       uniform
11                  1      distance
12                  2       uniform
13                  2      distance
14                  3       uniform
15                  3      distance
16                  4       uniform
17                  4      distance
18                  9       uniform
19                  9      distance

                                               params  split0_test_score  \
0   {'metric': 'euclidean', 'n_neighbors': 1, 'wei...                1.0
1   {'metric': 'euclidean', 'n_neighbors': 1, 'wei...                1.0
2   {'metric': 'euclidean', 'n_neighbors': 2, 'wei...                1.0
3   {'metric': 'euclidean', 'n_neighbors': 2, 'wei...                1.0
4   {'metric': 'euclidean', 'n_neighbors': 3, 'wei...                1.0
5   {'metric': 'euclidean', 'n_neighbors': 3, 'wei...                1.0
6   {'metric': 'euclidean', 'n_neighbors': 4, 'wei...                1.0
7   {'metric': 'euclidean', 'n_neighbors': 4, 'wei...                1.0
8   {'metric': 'euclidean', 'n_neighbors': 9, 'wei...                1.0
9   {'metric': 'euclidean', 'n_neighbors': 9, 'wei...                1.0
10  {'metric': 'manhattan', 'n_neighbors': 1, 'wei...                1.0
11  {'metric': 'manhattan', 'n_neighbors': 1, 'wei...                1.0
12  {'metric': 'manhattan', 'n_neighbors': 2, 'wei...                1.0
13  {'metric': 'manhattan', 'n_neighbors': 2, 'wei...                1.0
14  {'metric': 'manhattan', 'n_neighbors': 3, 'wei...                1.0
15  {'metric': 'manhattan', 'n_neighbors': 3, 'wei...                1.0
16  {'metric': 'manhattan', 'n_neighbors': 4, 'wei...                1.0
17  {'metric': 'manhattan', 'n_neighbors': 4, 'wei...                1.0
18  {'metric': 'manhattan', 'n_neighbors': 9, 'wei...                1.0
19  {'metric': 'manhattan', 'n_neighbors': 9, 'wei...                1.0

    split1_test_score  split2_test_score  split3_test_score  \
0                 1.0           1.000000           1.000000
1                 1.0           1.000000           1.000000
2                 1.0           1.000000           1.000000
3                 1.0           1.000000           1.000000
4                 1.0           1.000000           1.000000
5                 1.0           1.000000           1.000000
6                 1.0           1.000000           1.000000
7                 1.0           1.000000           1.000000
8                 1.0           0.958333           0.958333
9                 1.0           1.000000           1.000000
10                1.0           1.000000           1.000000
11                1.0           1.000000           1.000000
12                1.0           1.000000           1.000000
13                1.0           1.000000           1.000000
14                1.0           1.000000           1.000000
15                1.0           1.000000           1.000000
16                1.0           1.000000           1.000000
17                1.0           1.000000           1.000000
18                1.0           1.000000           0.958333
19                1.0           1.000000           1.000000

    split4_test_score  mean_test_score  std_test_score  rank_test_score
0                 1.0         1.000000        0.000000                1
1                 1.0         1.000000        0.000000                1
2                 1.0         1.000000        0.000000                1
3                 1.0         1.000000        0.000000                1
4                 1.0         1.000000        0.000000                1
5                 1.0         1.000000        0.000000                1
6                 1.0         1.000000        0.000000                1
7                 1.0         1.000000        0.000000                1
8                 1.0         0.983333        0.020412               20
9                 1.0         1.000000        0.000000                1
10                1.0         1.000000        0.000000                1
11                1.0         1.000000        0.000000                1
12                1.0         1.000000        0.000000                1
13                1.0         1.000000        0.000000                1
14                1.0         1.000000        0.000000                1
15                1.0         1.000000        0.000000                1
16                1.0         1.000000        0.000000                1
17                1.0         1.000000        0.000000                1
18                1.0         0.991667        0.016667               19
19                1.0         1.000000        0.000000                1