In [82]:
import pandas as pd
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

In [83]:
data=pd.read_csv("shop_smart_ecommerce (1).csv")

In [84]:
data.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,1,1,1,1,Returning_Visitor,False,False
1,0,0.0,0,0.0,2,64.000000,0.00,0.10,0.0,0.0,Feb,2,2,1,2,Returning_Visitor,False,False
2,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,4,1,9,3,Returning_Visitor,False,False
3,0,0.0,0,0.0,2,2.666667,0.05,0.14,0.0,0.0,Feb,3,2,2,4,Returning_Visitor,False,False
4,0,0.0,0,0.0,10,627.500000,0.02,0.05,0.0,0.0,Feb,3,3,1,4,Returning_Visitor,True,False

In [85]:
data.isnull().sum()

Administrative             0
Administrative_Duration    0
Informational              0
Informational_Duration     0
ProductRelated             0
ProductRelated_Duration    0
BounceRates                0
ExitRates                  0
PageValues                 0
SpecialDay                 0
Month                      0
OperatingSystems           0
Browser                    0
Region                     0
TrafficType                0
VisitorType                0
Weekend                    0
Revenue                    0
dtype: int64

In [ ]:
preprocessor=ColumnTransformer(
 transoformer=[
 ("num",StandardScaler(),num_features),
    ("cat",OneHotEncoder(handle_unknown="ignore"),cat_features)
 ])

dt=DecisionTreeClassifier

In [86]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()
data["Weekend"]=le.fit_transform(data["Weekend"])
data["Revenue"]=le.fit_transform(data["Revenue"])

data = pd.get_dummies(
    data,
    columns=["VisitorType", "Month"],
    drop_first=True
)

In [87]:
data.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,...,VisitorType_Returning_Visitor,Month_Dec,Month_Feb,Month_Jul,Month_June,Month_Mar,Month_May,Month_Nov,Month_Oct,Month_Sep
0,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,...,True,False,True,False,False,False,False,False,False,False
1,0,0.0,0,0.0,2,64.000000,0.00,0.10,0.0,0.0,...,True,False,True,False,False,False,False,False,False,False
2,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,...,True,False,True,False,False,False,False,False,False,False
3,0,0.0,0,0.0,2,2.666667,0.05,0.14,0.0,0.0,...,True,False,True,False,False,False,False,False,False,False
4,0,0.0,0,0.0,10,627.500000,0.02,0.05,0.0,0.0,...,True,False,True,False,False,False,False,False,False,False

In [88]:
corr_with_target = data.corr()["Revenue"]
print(corr_with_target)

Administrative                   0.138917
Administrative_Duration          0.093587
Informational                    0.095200
Informational_Duration           0.070345
ProductRelated                   0.158538
ProductRelated_Duration          0.152373
BounceRates                     -0.150673
ExitRates                       -0.207071
PageValues                       0.492569
SpecialDay                      -0.082305
OperatingSystems                -0.014668
Browser                          0.023984
Region                          -0.011595
TrafficType                     -0.005113
Weekend                          0.029295
Revenue                          1.000000
VisitorType_Other                0.007715
VisitorType_Returning_Visitor   -0.103843
Month_Dec                       -0.033112
Month_Feb                       -0.047114
Month_Jul                       -0.001036
Month_June                      -0.023112
Month_Mar                       -0.063941
Month_May                       -0.078320
Month_Nov                        0.154774
Month_Oct                        0.032666
Month_Sep                        0.019983
Name: Revenue, dtype: float64

In [89]:
X=data.drop("Revenue",axis=1)
y=data["Revenue"]

In [90]:
X_train,X_test,y_train,y_test=train_test_split(X ,y,test_size=0.3,random_state=42)

In [91]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import f1_score

model=DecisionTreeClassifier(max_depth=5)
model.fit(X_train,y_train)

score=model.score(X_test,y_test)
print(score*100)

89.61881589618817

In [95]:
max_depth = [5,3,6,7,8,9,2]

for depth in max_depth:
    model = DecisionTreeClassifier(max_depth=depth,random_state=42)
    model.fit(X_train, y_train)
    y_pred=model.predict(X_test)
    f1 = f1_score(y_test, y_pred)    
    print(f1)
    score = model.score(X_test, y_test)
    print(f"depth {depth} accuracy {score}")

0.6097560975609756
depth 5 accuracy 0.8961881589618816
0.6288372093023256
depth 3 accuracy 0.8921330089213301
0.6219151036525172
depth 6 accuracy 0.8964585022979183
0.6320754716981132
depth 7 accuracy 0.894566098945661
0.601980198019802
depth 8 accuracy 0.8913219789132197
0.6062846580406654
depth 9 accuracy 0.8848337388483374
0.5305676855895196
depth 2 accuracy 0.8837523655041903